### ISSUE TITLE
Proof of Stake, where is it?

### ISSUE THREAD

**Issue by Angus23203** [disy-yin/waltonchain-gwtc#10]
Maybe not an issue but I can't seem to find the Proof of Stake implementation that should work next to PoW.
Am I missing something or is it not implemented yet?

**Comment by disy-yin** [comment]
Take a look at the "CodeAge" section.This is POS related.

**Comment by Angus23203** [comment]
Ahh, you changed CodeAge into CoinAge, already thought it was 👍 
I agree this is POS related. It lowers difficulty based on your stake and coinage. However it still requires PoW mining. 

I was wondering where i could find the PoS implementation for which 1000000 WTC was reserved and a minimum of 50 WTC is needed which was mentioned in this document:
https://www.waltonchain.org/templets/default/doc/Waltonchain_Progressive_Mining_Reward_Program.pdf

**Comment by plalx** [comment]
@disy-yin Any update on this? That's quite important.

**Comment by disy-yin** [comment]
POS function is ok.
I will close this issue.

**Comment by Angus23203** [comment]
@disy-yin 
You didnt answer the question yet:

I was wondering where i could find the PoS implementation for which 1000000 WTC was reserved and a minimum of 50 WTC is needed which was mentioned in this document:
https://www.waltonchain.org/templets/default/doc/Waltonchain_Progressive_Mining_Reward_Program.pdf
