### ISSUE TITLE
fail to build with go 1.12 it doesn't understand I got a higher version number.

### ISSUE THREAD

**Issue by martincyprus** [disy-yin/waltonchain-gwtc#3]
Building with Go 1.12 on ubuntu 18.04 LTS.

```
waltonchain-gwtc$ make gwtc
build/env.sh go run build/ci.go install ./cmd/gwtc
ci.go:180: You have Go version go1.12
ci.go:181: go-wtc requires at least Go version 1.7 and cannot
ci.go:182: be compiled with an earlier version. Please upgrade your Go installation.
exit status 1
Makefile:15: recipe for target 'gwtc' failed
make: *** [gwtc] Error 1
```

easy to work around, but should be fixed.

**Comment by TkTzLabs** [comment]
Hello just to confirm **go 1.12 is not higher than 1.7 right ?** I am running on go version go1.7.6 linux/amd64
 without any issues.

**Comment by maddoc41** [comment]
mine worked only with go 1.7.6 (ubuntu 16.04 on MacOS Parallels)

**Comment by disy-yin** [comment]
go-wtc requires at least Go version 1.7

**Comment by maddoc41** [comment]
i know, but 1.8 also failed, and 1.12 (2019) was released later than 1.7 (2016), so it should be higher, shouldn't it

**Comment by disy-yin** [comment]
> I know, but 1.8 also failed, and 1.12 (2019) was released later than 1.7 (2016), so it should be higher, shouldn't it

Indeed, the version is too high is not allowed.
So,please install the go version 1.7.6

**Comment by martincyprus** [comment]
as has been stated, version 1.12 is much newer then 1.7, problem is that the "runtime.getVersion()" just returns a string, comparing strings for version is never a safe way, especially when going between version 9 and 10, as a pure string it will see the nine as much bigger value than 1 and 0, its just simple string compare.

I'm running successfully on 1.12 no problem, been mining away, everything compiles I'm not sure why you would want to restrict specifically to 1.7.6? which is now several years old..

**Comment by disy-yin** [comment]
> as has been stated, version 1.12 is much newer then 1.7, problem is that the "runtime.getVersion()" just returns a string, comparing strings for version is never a safe way, especially when going between version 9 and 10, as a pure string it will see the nine as much bigger value than 1 and 0, its just simple string compare.
> 
> I'm running successfully on 1.12 no problem, been mining away, everything compiles I'm not sure why you would want to restrict specifically to 1.7.6? which is now several years old..
> 
> I have a patch ready if you accept pull requests that will make it truly version 1.7+

Thank you. Good job!
We accept pull requests.

**Comment by martincyprus** [comment]
great, out with kids right now, will put it in, in a couple of hours. thanks.
