### ISSUE TITLE
!!No Issue__Get extra Data Blocks displayed

### ISSUE THREAD

**Issue by maddoc41** [disy-yin/waltonchain-gwtc#8]
if anybody set extradata {miner.setExtra("MINER_NAME")}, here is how you can read out (copied from waltonchain)

function into console:

function minedBlocks(lastn, addr, findit) {
  addrs = [];
  if (!addr) {
    addr = eth.coinbase
  }
  if(findit)
  {
     findit = findit.toLowerCase()
  }
  limit = eth.blockNumber - lastn
  for (i = eth.blockNumber; i >= limit; i--) {
    if (eth.getBlock(i).miner == addr) {
        if(findit)
        {
        extra = web3.toAscii(eth.getBlock(i).extraData)
        if (extra .toLowerCase().indexOf(findit) != -1)
        {
            addrs.push("Block " + i + ": " + extra)
        }
        }else
        {
        extra = web3.toAscii(eth.getBlock(i).extraData)
        addrs.push("Block " + i + ": " + extra)
        }
    }
  }
  return addrs
}

run function with something like 1000 or 3000 blocks and your Miner Name

e.g:
 minedBlocks(1000, wtc.coinbase, "MINER_NAME");

Enjoy!!

**Comment by AboldUSER** [comment]
In the above code, do you need to change everything that is 'eth' to 'wtc'?

**Comment by maddoc41** [comment]
you could change everything to wtc, but it works with eth as well

**Comment by maddoc41** [comment]
so, just to make sure we have a clean eth fork:

function minedBlocks(lastn, addr, findit) {
addrs = [];
if (!addr) {
addr = wtc.coinbase
}
if(findit)
{
findit = findit.toLowerCase()
}
limit = wtc.blockNumber - lastn
for (i = wtc.blockNumber; i >= limit; i--) {
if (wtc.getBlock(i).miner == addr) {
if(findit)
{
extra = web3.toAscii(wtc.getBlock(i).extraData)
if (extra .toLowerCase().indexOf(findit) != -1)
{
addrs.push("Block " + i + ": " + extra)
}
}else
{
extra = web3.toAscii(wtc.getBlock(i).extraData)
addrs.push("Block " + i + ": " + extra)
}
}
}
return addrs
}
